/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pro_bibliotecajuegos.view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JProgressBar;
import javax.swing.JTextField;
import javax.swing.Timer;
import pro_bibliotecajuegos.controller.TrivialController;

/**
 *
 * @author Hansen
 */
public class TrivialQuestionView extends javax.swing.JFrame {

    TrivialController control = new TrivialController();

    private Timer t;
    private ActionListener al;

    /**
     * Creates new form TrivialQuestionView
     */
    public TrivialQuestionView() {
        // Se instancia el ActionListener:
        al = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                if (jProgressBar1.getValue() < 100) {
                    jProgressBar1.setValue(jProgressBar1.getValue() + 10);
                } else {
                    t.stop();
                    jtTextoPregunta.setText("O tempo terminou, preme 'Seguinte Pregunta' para continuar.");
                    control.bloquearBotones(bPregunta1, bPregunta2, bPregunta3, bPregunta4);
                }
            }
        };
        // Avanza cada 1000 milisegundos y se le asigna el ActionListener al:
        t = new Timer(1000, al);
        initComponents();
        t.start();
        if (jProgressBar1.getValue() < 100) {
            jProgressBar1.setValue(jProgressBar1.getValue() + 10);
        } else {
            t.stop();
        }
    }

    public JButton getbSiguientePregunta() {
        return bSiguientePregunta;
    }

    public void setbSiguientePregunta(JButton bSiguientePregunta) {
        this.bSiguientePregunta = bSiguientePregunta;
    }

    public JProgressBar getjProgressBar1() {
        return jProgressBar1;
    }

    public void setjProgressBar1(JProgressBar jProgressBar1) {
        this.jProgressBar1 = jProgressBar1;
    }

    public JLabel getJtNombreJugador() {
        return jtNombreJugador;
    }

    public void setJtNombreJugador(JLabel jtNombreJugador) {
        this.jtNombreJugador = jtNombreJugador;
    }

    public JLabel getJtScore() {
        return jtScore;
    }

    public void setJtScore(JLabel jtScore) {
        this.jtScore = jtScore;
    }

    public JLabel getJtTipoPregunta() {
        return jtTipoPregunta;
    }

    public void setJtTipoPregunta(JLabel jtTipoPregunta) {
        this.jtTipoPregunta = jtTipoPregunta;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBase = new javax.swing.JPanel();
        panelScore = new javax.swing.JPanel();
        jtTipoPregunta = new javax.swing.JLabel();
        jtScore = new javax.swing.JLabel();
        jtNombreJugador = new javax.swing.JLabel();
        jtTextoPregunta = new javax.swing.JTextField();
        jProgressBar1 = new javax.swing.JProgressBar();
        bPregunta1 = new javax.swing.JButton();
        bPregunta2 = new javax.swing.JButton();
        bPregunta3 = new javax.swing.JButton();
        bPregunta4 = new javax.swing.JButton();
        bSiguientePregunta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelBase.setBackground(new java.awt.Color(102, 102, 255));

        panelScore.setBackground(new java.awt.Color(0, 51, 102));

        jtTipoPregunta.setForeground(new java.awt.Color(255, 255, 255));
        jtTipoPregunta.setText("Tipo de pregunta");

        jtScore.setForeground(new java.awt.Color(255, 255, 255));
        jtScore.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jtScore.setText("Score: 0000");

        jtNombreJugador.setForeground(new java.awt.Color(255, 255, 255));
        jtNombreJugador.setText("Nombre Jugador");

        javax.swing.GroupLayout panelScoreLayout = new javax.swing.GroupLayout(panelScore);
        panelScore.setLayout(panelScoreLayout);
        panelScoreLayout.setHorizontalGroup(
            panelScoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelScoreLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtTipoPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jtNombreJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jtScore, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelScoreLayout.setVerticalGroup(
            panelScoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelScoreLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelScoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtTipoPregunta)
                    .addComponent(jtScore)
                    .addComponent(jtNombreJugador))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtTextoPregunta.setEditable(false);
        jtTextoPregunta.setBackground(new java.awt.Color(0, 0, 0));
        jtTextoPregunta.setForeground(new java.awt.Color(255, 255, 255));
        jtTextoPregunta.setText("Texto de la pregunta");

        jProgressBar1.setForeground(new java.awt.Color(0, 153, 0));

        bPregunta1.setText("Pregunta 1");
        bPregunta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPregunta1ActionPerformed(evt);
            }
        });

        bPregunta2.setText("Pregunta 2");
        bPregunta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPregunta2ActionPerformed(evt);
            }
        });

        bPregunta3.setText("Pregunta 3");
        bPregunta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPregunta3ActionPerformed(evt);
            }
        });

        bPregunta4.setText("Pregunta 4");
        bPregunta4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPregunta4ActionPerformed(evt);
            }
        });

        bSiguientePregunta.setText("Siguiente pregunta");
        bSiguientePregunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSiguientePreguntaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBaseLayout = new javax.swing.GroupLayout(panelBase);
        panelBase.setLayout(panelBaseLayout);
        panelBaseLayout.setHorizontalGroup(
            panelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelScore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelBaseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtTextoPregunta))
                .addContainerGap())
            .addGroup(panelBaseLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(panelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bSiguientePregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bPregunta4, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bPregunta3, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bPregunta2, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bPregunta1, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBaseLayout.setVerticalGroup(
            panelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBaseLayout.createSequentialGroup()
                .addComponent(panelScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtTextoPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bPregunta1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bPregunta2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bPregunta3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bPregunta4)
                .addGap(87, 87, 87)
                .addComponent(bSiguientePregunta)
                .addGap(0, 14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bPregunta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPregunta1ActionPerformed
        control.bloquearBotones(bPregunta1, bPregunta2, bPregunta3, bPregunta4);
        t.stop();
    }//GEN-LAST:event_bPregunta1ActionPerformed

    private void bPregunta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPregunta2ActionPerformed
        control.bloquearBotones(bPregunta1, bPregunta2, bPregunta3, bPregunta4);
        t.stop();
    }//GEN-LAST:event_bPregunta2ActionPerformed

    private void bPregunta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPregunta3ActionPerformed
        control.bloquearBotones(bPregunta1, bPregunta2, bPregunta3, bPregunta4);
        t.stop();
    }//GEN-LAST:event_bPregunta3ActionPerformed

    private void bPregunta4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPregunta4ActionPerformed
        control.bloquearBotones(bPregunta1, bPregunta2, bPregunta3, bPregunta4);
        t.stop();
    }//GEN-LAST:event_bPregunta4ActionPerformed

    private void bSiguientePreguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSiguientePreguntaActionPerformed
        dispose();
    }//GEN-LAST:event_bSiguientePreguntaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrivialQuestionView().setVisible(true);
            }
        });
    }

    public void setbPregunta1(JButton bPregunta1) {
        this.bPregunta1 = bPregunta1;
    }

    public void setbPregunta2(JButton bPregunta2) {
        this.bPregunta2 = bPregunta2;
    }

    public void setbPregunta3(JButton bPregunta3) {
        this.bPregunta3 = bPregunta3;
    }

    public void setbPregunta4(JButton bPregunta4) {
        this.bPregunta4 = bPregunta4;
    }

    public void setJtTextoPregunta(JTextField jtTextoPregunta) {
        this.jtTextoPregunta = jtTextoPregunta;
    }

    public JButton getbPregunta1() {
        return bPregunta1;
    }

    public JButton getbPregunta2() {
        return bPregunta2;
    }

    public JButton getbPregunta3() {
        return bPregunta3;
    }

    public JButton getbPregunta4() {
        return bPregunta4;
    }

    public JTextField getJtTextoPregunta() {
        return jtTextoPregunta;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bPregunta1;
    private javax.swing.JButton bPregunta2;
    private javax.swing.JButton bPregunta3;
    private javax.swing.JButton bPregunta4;
    private javax.swing.JButton bSiguientePregunta;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel jtNombreJugador;
    private javax.swing.JLabel jtScore;
    private javax.swing.JTextField jtTextoPregunta;
    private javax.swing.JLabel jtTipoPregunta;
    private javax.swing.JPanel panelBase;
    private javax.swing.JPanel panelScore;
    // End of variables declaration//GEN-END:variables
}
